### ISSUE TITLE
sorting by area and overlap enlargement

### ISSUE THREAD

**Issue by zhouzuoshui** [virtuald/r-star-tree#2]
Thank you for implementation, it's really great!

Only one question, about the functor. according to the paper of Beckmann et al., when we sort items by area enlargement, the functor should expand both subtrees, which are passed to member function () as parameters, to contain the target node, passed to constructor as param., then we compare two delta areas after and before expansion, and choose the smaller.

And for overlap enlargement, we firstly expand all or selected inner subtrees to contain the new node, then compute the overlap to the other silbings, the delta diff. of overlap, after and before expansion, should be the criterium for compare.

Did I missunderstand the paper or your code?

**Comment by virtuald** [comment]
I wrote this almost a decade ago, so unfortunately I don't remember the answer. One thing this implementation is severely lacking is proper tests, so it's hard to say whether it does the right thing or not.

**Comment by zhouzuoshui** [comment]
Oh,,, OK, thanks anyway.

**Comment by virtuald** [comment]
Sorry, good luck!
